apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-kaniko-build
  namespace: ia-hattorihrd-ns-tekton
spec:
  inputs:
    resources:
      - name: git-resource
        type: git
  outputs:
    resources:
      - name: node-app-image
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
      - --dockerfile=/workspace/git-resource/src/node-app/Dockerfile
      - --destination=hattorihrd/node-app:latest
      - --context=/workspace/git-resource/src/node-app
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-deploy
  namespace: ia-hattorihrd-ns-tekton
spec:
  inputs:
    resources:
      - name: git-resource
        type: git
  steps:
    - name: step-deploy
      image: lachlanevenson/k8s-kubectl
      command:
        - kubectl
      args:
      - "apply"
      - "-f"
      - "/workspace/git-resource/service-deployment.yaml"
