---
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-admin
  namespace: ia-hattorihrd-ns-tekton
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - triggers
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - clustertriggerbindings
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  - taskruns
  verbs:
  - create
  - list
  - watch
  - delete #add
  - get #add
  - update #add
  - deletecollection #add
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups: 
  - ""
  resources: 
  - serviceaccounts
  verbs: 
  - impersonate
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - tekton-triggers
  verbs: 
  - use
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-admin
  namespace: ia-hattorihrd-ns-tekton
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-admin-binding
  namespace: ia-hattorihrd-ns-tekton
subjects:
- kind: ServiceAccount
  name: tekton-triggers-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-admin
---
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-admin-clusterrole
rules:
  # EventListeners need to be able to fetch any clustertriggerbindings
- apiGroups:
  - triggers.tekton.dev
  resources:
  - clustertriggerbindings
  verbs:
  - create
  - get
  - list
  - watch
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-admin-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-admin
  namespace: ia-hattorihrd-ns-tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-admin-clusterrole
---
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: pipeline-clusterbinding
  namespace : ia-hattorihrd-ns-tekton
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: contenttype
      value: $(header.Content-Type)
---
#fin
