apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: YOUR-INGRESS-NAME
  namespace: YOUR-NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "YOUR-FQDN"
      http:
        paths:
          - backend:
              serviceName: YOUR-INGRESS-NAME
              servicePort: 8080
---
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "YOUR-FQDN"
      http:
        paths:
          - backend:
              serviceName: tekton-dashboard
              servicePort: 9097
