apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: YOUR-TRIGGERTEMPLATE-NAME
  namespace: YOUR-NAMESPACE
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-build-deploy-run-
        namespace: YOUR-NAMESPACE
      spec:
        serviceAccountName: YOUR-SERVICEACCOUTNAME
        params:
          - name: gitrevision
            value: $(tt.params.gitrevision)
        pipelineRef:
          name: pipeline-build-deploy
        resources:     
          - name: pipeline-git
            resourceRef:
              name: git-resource
          - name: pipeline-image
            resourceRef:
              name: node-app-image
      status: {}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: YOUR-TRIGGERBINDING-NAME
  namespace: YOUR-NAMESPACE
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: YOUR-NAMESPACE
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: YOUR-EVENTLISTNER-NAME
  namespace: YOUR-NAMESPACE
spec: 
  serviceAccountName: tekton-triggers-admin
  triggers:
    - bindings:
      - ref: YOUR-TRIGGERBINDING-NAME
      template:
        ref: YOUR-TRIGGERTEMPLATE-NAME
---
#fin
