apiVersion: v1
kind: Secret
metadata:
  name: YOUR-SECRET-NAME
  namespace: YOUR-NAMESPACE
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: YOUR-RESISTORY-USERNAME
  password: YOUR-RESISTORY-PASSWORD
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: YOUR-SERVICEACCOUT-NAME
  namespace: YOUR-NAMESPACE
secrets:
  - name: YOUR-SECRET-NAME
