apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-resource
  namespace: ia-hattorihrd-ns-tekton
spec:
  type: git
  params:
  - name: url
    value: https://github.com/hattorihrd/tkn-app.git
  - name: revision
    value: main

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: node-app-image
  namespace: ia-hattorihrd-ns-tekton
spec:
  type: image
  params:
  - name: url
    value: hattorihrd/node-app:latest
