apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  namespace: YOUR-NAMESPACE-NAME
  generateName: taskrun-kaniko-build-
spec:
  serviceAccountName: YOUR-SERVICEACCOUTNAME
  taskRef:
    name: task-kaniko-build
  inputs:
    resources:
    - name: git-resource
      resourceRef:
        name: git-resource
  outputs:
    resources:
    - name: node-app-image
      resourceRef:
        name: node-app-image
